# site settings
title: Madeline Grosklos Portfolio
subtitle: Biomehanics researcher 
email: grosklos.2@osu.edu
description: Portfolio of projects, education, and leadership in biomedical engineering and musculoskeletal biomechanics. 
baseurl: #"/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
500px_url:
facebook_url:
github_url: https://maddiegrosklos.github.io
gitlab_url: 
googleplus_url: 
instagram_url: 
envelope: mailto:grosklos.2@osu.edu
LinkedIn: https://www.linkedin.com/in/madeline-grosklos-9871b99a/
globe: https://maddiegrosklos.github.io
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
